namespace nlohmann {
template <> struct adl_serializer<std::any> {
    static void to_json(json& j, const std::any& v) {
        if (!v.has_value()) { j = nullptr; return; }
        const auto& ti = v.type();
        if (ti == typeid(int64_t)) { j = std::any_cast<int64_t>(v); return; }
        if (ti == typeid(int)) { j = std::any_cast<int>(v); return; }
        if (ti == typeid(bool)) { j = std::any_cast<bool>(v); return; }
        if (ti == typeid(std::string)) { j = std::any_cast<std::string>(v); return; }
        if (ti == typeid(double)) { j = std::any_cast<double>(v); return; }
        if (ti == typeid(asn1::runtime::BitString)) { j = std::any_cast<asn1::runtime::BitString>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_CommonDataTypes::PrivateIE_ID)) { j = std::any_cast<asn1::generated::E1AP_CommonDataTypes::PrivateIE_ID>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_Containers::ProtocolIE_Field)) { j = std::any_cast<asn1::generated::E1AP_Containers::ProtocolIE_Field>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_Containers::ProtocolIE_Container)) { j = std::any_cast<asn1::generated::E1AP_Containers::ProtocolIE_Container>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_Containers::ProtocolIE_ContainerList)) { j = std::any_cast<asn1::generated::E1AP_Containers::ProtocolIE_ContainerList>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_Containers::ProtocolExtensionField)) { j = std::any_cast<asn1::generated::E1AP_Containers::ProtocolExtensionField>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_Containers::ProtocolExtensionContainer)) { j = std::any_cast<asn1::generated::E1AP_Containers::ProtocolExtensionContainer>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_Containers::PrivateIE_Field)) { j = std::any_cast<asn1::generated::E1AP_Containers::PrivateIE_Field>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_Containers::PrivateIE_Container)) { j = std::any_cast<asn1::generated::E1AP_Containers::PrivateIE_Container>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cause_radioNetwork)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cause_radioNetwork>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cause_transport)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cause_transport>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cause_protocol)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cause_protocol>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cause_misc)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cause_misc>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cause_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cause_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cause)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cause>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::CommonNetworkInstance)) { j = std::any_cast<asn1::generated::E1AP_IEs::CommonNetworkInstance>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Activity_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Activity_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Activity_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Activity_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_Mod_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_Mod_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_Mod_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_Mod_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_Mod_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_Mod_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_Mod_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_Mod_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Failed_To_Modify_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Remove_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Remove_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Remove_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Remove_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Remove_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Remove_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Remove_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Remove_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Remove_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Remove_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Remove_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Remove_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Remove_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Remove_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Remove_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Remove_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Usage_Report_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Usage_Report_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Usage_Report_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Usage_Report_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::EncryptionKey)) { j = std::any_cast<asn1::generated::E1AP_IEs::EncryptionKey>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GBR_QosInformation)) { j = std::any_cast<asn1::generated::E1AP_IEs::GBR_QosInformation>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GTP_TEID)) { j = std::any_cast<asn1::generated::E1AP_IEs::GTP_TEID>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::IntegrityProtectionKey)) { j = std::any_cast<asn1::generated::E1AP_IEs::IntegrityProtectionKey>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::MaximumIPdatarate)) { j = std::any_cast<asn1::generated::E1AP_IEs::MaximumIPdatarate>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GBR_QoSFlowInformation)) { j = std::any_cast<asn1::generated::E1AP_IEs::GBR_QoSFlowInformation>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::MRDC_Data_Usage_Report_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::MRDC_Data_Usage_Report_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Data_Usage_per_PDU_Session_Report)) { j = std::any_cast<asn1::generated::E1AP_IEs::Data_Usage_per_PDU_Session_Report>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PacketErrorRate)) { j = std::any_cast<asn1::generated::E1AP_IEs::PacketErrorRate>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDCP_Count)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDCP_Count>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Status_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Status_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRBBStatusTransfer)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRBBStatusTransfer>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDCP_SN_Status_Information)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDCP_SN_Status_Information>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRBs_Subject_To_Counter_Check_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Activity_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Activity_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Activity_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Activity_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_Mod_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_Mod_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_Mod_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_Mod_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_To_Modify_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_To_Modify_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_To_Modify_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Failed_To_Modify_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Remove_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Remove_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Remove_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Remove_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PLMN_Identity)) { j = std::any_cast<asn1::generated::E1AP_IEs::PLMN_Identity>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::NR_CGI)) { j = std::any_cast<asn1::generated::E1AP_IEs::NR_CGI>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::NR_CGI_Support_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::NR_CGI_Support_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::NR_CGI_Support_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::NR_CGI_Support_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::EUTRANAllocationAndRetentionPriority)) { j = std::any_cast<asn1::generated::E1AP_IEs::EUTRANAllocationAndRetentionPriority>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::NGRANAllocationAndRetentionPriority)) { j = std::any_cast<asn1::generated::E1AP_IEs::NGRANAllocationAndRetentionPriority>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::EUTRAN_QoS)) { j = std::any_cast<asn1::generated::E1AP_IEs::EUTRAN_QoS>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::EUTRAN_QoS_Support_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::EUTRAN_QoS_Support_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::EUTRAN_QoS_Support_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::EUTRAN_QoS_Support_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Data_Usage_per_QoS_Flow_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::Data_Usage_per_QoS_Flow_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Data_Usage_per_QoS_Flow_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::Data_Usage_per_QoS_Flow_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::MRDC_Usage_Information)) { j = std::any_cast<asn1::generated::E1AP_IEs::MRDC_Usage_Information>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Data_Usage_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Data_Usage_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Data_Usage_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Data_Usage_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_To_Notify_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_To_Notify_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_To_Notify_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_To_Notify_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_Failed_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_Failed_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_Failed_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_Failed_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_Mapping_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_Mapping_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_Mapping_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_Mapping_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Data_Forwarding_Information_Request)) { j = std::any_cast<asn1::generated::E1AP_IEs::Data_Forwarding_Information_Request>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Dynamic5QIDescriptor)) { j = std::any_cast<asn1::generated::E1AP_IEs::Dynamic5QIDescriptor>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Non_Dynamic5QIDescriptor)) { j = std::any_cast<asn1::generated::E1AP_IEs::Non_Dynamic5QIDescriptor>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::NG_RAN_QoS_Support_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::NG_RAN_QoS_Support_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::NG_RAN_QoS_Support_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::NG_RAN_QoS_Support_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Characteristics_non_Dynamic_5QI)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Characteristics_non_Dynamic_5QI>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Characteristics_dynamic_5QI)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Characteristics_dynamic_5QI>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Characteristics_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Characteristics_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Characteristics)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Characteristics>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Parameters_Support_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Parameters_Support_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoSFlowLevelQoSParameters)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoSFlowLevelQoSParameters>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_QoS_Parameter_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_QoS_Parameter_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::QoS_Flow_QoS_Parameter_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::QoS_Flow_QoS_Parameter_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::RANUEID)) { j = std::any_cast<asn1::generated::E1AP_IEs::RANUEID>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Data_Usage_Report_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::Data_Usage_Report_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Data_Usage_Report_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::Data_Usage_Report_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ROHC)) { j = std::any_cast<asn1::generated::E1AP_IEs::ROHC>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::SecurityAlgorithm)) { j = std::any_cast<asn1::generated::E1AP_IEs::SecurityAlgorithm>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::SecurityIndication)) { j = std::any_cast<asn1::generated::E1AP_IEs::SecurityIndication>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::SecurityResult)) { j = std::any_cast<asn1::generated::E1AP_IEs::SecurityResult>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::SNSSAI)) { j = std::any_cast<asn1::generated::E1AP_IEs::SNSSAI>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Slice_Support_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::Slice_Support_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Slice_Support_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::Slice_Support_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::SDAP_Configuration)) { j = std::any_cast<asn1::generated::E1AP_IEs::SDAP_Configuration>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::CP_TNL_Information_endpoint_IP_Address)) { j = std::any_cast<asn1::generated::E1AP_IEs::CP_TNL_Information_endpoint_IP_Address>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::CP_TNL_Information_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_IEs::CP_TNL_Information_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::CP_TNL_Information)) { j = std::any_cast<asn1::generated::E1AP_IEs::CP_TNL_Information>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Endpoint_IP_address_and_port)) { j = std::any_cast<asn1::generated::E1AP_IEs::Endpoint_IP_address_and_port>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_Setup_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_Setup_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_Failed_To_Setup_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_Failed_To_Setup_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_To_Add_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_To_Add_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_To_Remove_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_To_Remove_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_To_Update_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_CP_TNLA_To_Update_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_UP_TNLA_To_Remove_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_UP_TNLA_To_Remove_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GTPTunnel)) { j = std::any_cast<asn1::generated::E1AP_IEs::GTPTunnel>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::T_ReorderingTimer)) { j = std::any_cast<asn1::generated::E1AP_IEs::T_ReorderingTimer>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::CriticalityDiagnostics_IE_List_element)) { j = std::any_cast<asn1::generated::E1AP_IEs::CriticalityDiagnostics_IE_List_element>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::CriticalityDiagnostics_IE_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::CriticalityDiagnostics_IE_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::CriticalityDiagnostics)) { j = std::any_cast<asn1::generated::E1AP_IEs::CriticalityDiagnostics>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ActivityInformation_dRB_Activity_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::ActivityInformation_dRB_Activity_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ActivityInformation_pDU_Session_Resource_Activity_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::ActivityInformation_pDU_Session_Resource_Activity_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ActivityInformation_uE_Activity)) { j = std::any_cast<asn1::generated::E1AP_IEs::ActivityInformation_uE_Activity>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ActivityInformation_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_IEs::ActivityInformation_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ActivityInformation)) { j = std::any_cast<asn1::generated::E1AP_IEs::ActivityInformation>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UE_associatedLogicalE1_ConnectionItem)) { j = std::any_cast<asn1::generated::E1AP_IEs::UE_associatedLogicalE1_ConnectionItem>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cell_Group_Information_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cell_Group_Information_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Cell_Group_Information)) { j = std::any_cast<asn1::generated::E1AP_IEs::Cell_Group_Information>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Confirm_Modified_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Confirm_Modified_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Confirm_Modified_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Confirm_Modified_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Confirm_Modified_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Confirm_Modified_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Confirm_Modified_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Confirm_Modified_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Confirm_Modified_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Confirm_Modified_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Confirm_Modified_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Confirm_Modified_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UPSecuritykey)) { j = std::any_cast<asn1::generated::E1AP_IEs::UPSecuritykey>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::SecurityInformation)) { j = std::any_cast<asn1::generated::E1AP_IEs::SecurityInformation>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UP_TNL_Information_gTPTunnel)) { j = std::any_cast<asn1::generated::E1AP_IEs::UP_TNL_Information_gTPTunnel>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UP_TNL_Information_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_IEs::UP_TNL_Information_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UP_TNL_Information)) { j = std::any_cast<asn1::generated::E1AP_IEs::UP_TNL_Information>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::Data_Forwarding_Information)) { j = std::any_cast<asn1::generated::E1AP_IEs::Data_Forwarding_Information>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_UP_CellGroupRelatedConfiguration_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_UP_CellGroupRelatedConfiguration_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::GNB_CU_UP_CellGroupRelatedConfiguration)) { j = std::any_cast<asn1::generated::E1AP_IEs::GNB_CU_UP_CellGroupRelatedConfiguration>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Modify_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Modify_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Modify_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Modify_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Modify_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Modify_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Required_To_Modify_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Required_To_Modify_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Required_To_Modify_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Required_To_Modify_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Required_To_Modify_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Required_To_Modify_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UP_Parameters_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::UP_Parameters_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UP_Parameters)) { j = std::any_cast<asn1::generated::E1AP_IEs::UP_Parameters>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Modified_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Modified_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Modified_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Modified_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Modified_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Modified_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Modified_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Modified_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_Mod_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_Mod_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_Mod_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_Mod_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_Mod_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_Mod_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_Setup_Mod_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_Setup_Mod_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Modified_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Modified_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Modified_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Modified_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_Mod_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_Mod_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_Mod_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_Setup_Mod_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::UplinkOnlyROHC)) { j = std::any_cast<asn1::generated::E1AP_IEs::UplinkOnlyROHC>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ROHC_Parameters_rOHC)) { j = std::any_cast<asn1::generated::E1AP_IEs::ROHC_Parameters_rOHC>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ROHC_Parameters_uPlinkOnlyROHC)) { j = std::any_cast<asn1::generated::E1AP_IEs::ROHC_Parameters_uPlinkOnlyROHC>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ROHC_Parameters_choice_Extension)) { j = std::any_cast<asn1::generated::E1AP_IEs::ROHC_Parameters_choice_Extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::ROHC_Parameters)) { j = std::any_cast<asn1::generated::E1AP_IEs::ROHC_Parameters>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDCP_Configuration)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDCP_Configuration>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Modify_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Modify_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Modify_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Modify_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Modify_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Modify_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Modify_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Modify_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_Item_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_Item_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_List_EUTRAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_List_EUTRAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_Item_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_Item_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_List_NG_RAN)) { j = std::any_cast<asn1::generated::E1AP_IEs::DRB_To_Setup_Mod_List_NG_RAN>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Modify_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Modify_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Modify_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Modify_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_Mod_Item)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_Mod_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_Mod_List)) { j = std::any_cast<asn1::generated::E1AP_IEs::PDU_Session_Resource_To_Setup_Mod_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::Reset)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::Reset>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::UE_associatedLogicalE1_ConnectionListRes)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::UE_associatedLogicalE1_ConnectionListRes>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::ResetType_e1_Interface)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::ResetType_e1_Interface>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::ResetType_partOfE1_Interface)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::ResetType_partOfE1_Interface>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::ResetType_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::ResetType_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::ResetType)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::ResetType>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::ResetAcknowledge)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::ResetAcknowledge>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::UE_associatedLogicalE1_ConnectionListResAck)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::UE_associatedLogicalE1_ConnectionListResAck>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::ErrorIndication)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::ErrorIndication>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_E1SetupRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_E1SetupRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::SupportedPLMNs_Item)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::SupportedPLMNs_Item>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::SupportedPLMNs_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::SupportedPLMNs_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_E1SetupResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_E1SetupResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_E1SetupFailure)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_E1SetupFailure>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_E1SetupRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_E1SetupRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_E1SetupResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_E1SetupResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_E1SetupFailure)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_E1SetupFailure>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_ConfigurationUpdate)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_ConfigurationUpdate>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_TNLA_To_Remove_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_TNLA_To_Remove_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_ConfigurationUpdateAcknowledge)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_ConfigurationUpdateAcknowledge>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_ConfigurationUpdateFailure)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_ConfigurationUpdateFailure>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_ConfigurationUpdate)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_ConfigurationUpdate>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_To_Add_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_To_Add_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_To_Remove_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_To_Remove_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_To_Update_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_To_Update_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_ConfigurationUpdateAcknowledge)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_ConfigurationUpdateAcknowledge>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_Setup_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_Setup_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_Failed_To_Setup_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_TNLA_Failed_To_Setup_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_ConfigurationUpdateFailure)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_CP_ConfigurationUpdateFailure>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::E1ReleaseRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::E1ReleaseRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::E1ReleaseResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::E1ReleaseResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextSetupRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextSetupRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest_e_UTRAN_BearerContextSetupRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest_e_UTRAN_BearerContextSetupRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest_nG_RAN_BearerContextSetupRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest_nG_RAN_BearerContextSetupRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextSetupResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextSetupResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse_e_UTRAN_BearerContextSetupResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse_e_UTRAN_BearerContextSetupResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse_nG_RAN_BearerContextSetupResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse_nG_RAN_BearerContextSetupResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextSetupResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextSetupFailure)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextSetupFailure>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextModificationRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextModificationRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest_e_UTRAN_BearerContextModificationRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest_e_UTRAN_BearerContextModificationRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest_nG_RAN_BearerContextModificationRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest_nG_RAN_BearerContextModificationRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextModificationResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextModificationResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse_e_UTRAN_BearerContextModificationResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse_e_UTRAN_BearerContextModificationResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse_nG_RAN_BearerContextModificationResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse_nG_RAN_BearerContextModificationResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationResponse>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextModificationFailure)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextModificationFailure>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextModificationRequired)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextModificationRequired>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired_e_UTRAN_BearerContextModificationRequired)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired_e_UTRAN_BearerContextModificationRequired>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired_nG_RAN_BearerContextModificationRequired)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired_nG_RAN_BearerContextModificationRequired>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationRequired>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextModificationConfirm)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextModificationConfirm>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm_e_UTRAN_BearerContextModificationConfirm)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm_e_UTRAN_BearerContextModificationConfirm>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm_nG_RAN_BearerContextModificationConfirm)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm_nG_RAN_BearerContextModificationConfirm>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_BearerContextModificationConfirm>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextReleaseCommand)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextReleaseCommand>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextReleaseComplete)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextReleaseComplete>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextReleaseRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextReleaseRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::DRB_Status_List)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::DRB_Status_List>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::BearerContextInactivityNotification)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::BearerContextInactivityNotification>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::DLDataNotification)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::DLDataNotification>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::ULDataNotification)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::ULDataNotification>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::DataUsageReport)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::DataUsageReport>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_CounterCheckRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_CounterCheckRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest_e_UTRAN_GNB_CU_UP_CounterCheckRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest_e_UTRAN_GNB_CU_UP_CounterCheckRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest_nG_RAN_GNB_CU_UP_CounterCheckRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest_nG_RAN_GNB_CU_UP_CounterCheckRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest_choice_extension)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest_choice_extension>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::System_GNB_CU_UP_CounterCheckRequest>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_StatusIndication)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::GNB_CU_UP_StatusIndication>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::MRDC_DataUsageReport)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::MRDC_DataUsageReport>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Contents::PrivateMessage)) { j = std::any_cast<asn1::generated::E1AP_PDU_Contents::PrivateMessage>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Descriptions::InitiatingMessage)) { j = std::any_cast<asn1::generated::E1AP_PDU_Descriptions::InitiatingMessage>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Descriptions::SuccessfulOutcome)) { j = std::any_cast<asn1::generated::E1AP_PDU_Descriptions::SuccessfulOutcome>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Descriptions::UnsuccessfulOutcome)) { j = std::any_cast<asn1::generated::E1AP_PDU_Descriptions::UnsuccessfulOutcome>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU_initiatingMessage)) { j = std::any_cast<asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU_initiatingMessage>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU_successfulOutcome)) { j = std::any_cast<asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU_successfulOutcome>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU_unsuccessfulOutcome)) { j = std::any_cast<asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU_unsuccessfulOutcome>(v); return; }
        if (ti == typeid(asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU)) { j = std::any_cast<asn1::generated::E1AP_PDU_Descriptions::E1AP_PDU>(v); return; }
        j = nullptr;
    }
    static void from_json(const json& j, std::any& v) {
        // Default fallback to BitString for now
        if (j.is_object() && j.contains("hex") && j.contains("bit_length")) {
            asn1::runtime::BitString bs;
            bs.bit_length = j.at("bit_length").get<size_t>();
            std::string hex = j.at("hex").get<std::string>();
            for (size_t i = 0; i + 1 < hex.size(); i += 2)
                bs.data.push_back(static_cast<uint8_t>(std::stoul(hex.substr(i, 2), nullptr, 16)));
            v = std::move(bs);
        }
    }
};
} // namespace nlohmann
